apiVersion: apps/v1
kind: Deployment
metadata:
  name: goal
  labels:
    app: goal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goal
  template:
    metadata:
      labels:
        app: goal
    spec:
      containers:
      - name: goal
        image: hjsky1010/goal:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: goal-config
              key: DB_SERVER
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: goal-config
              key: DB_PORT
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: goal-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: goal-config
              key: DB_PASSWORD
        - name: SERVLET_CONTEXT_PATH
          valueFrom:
            configMapKeyRef:
              name: goal-config
              key: SERVLET_CONTEXT_PATH
